### ISSUE TITLE
Not compatible with GCC compiler on Debian 9 GNU/Linux

### ISSUE THREAD

**Issue by holishing** [ccns/dreamlandbbs#3]
trying to figure out the reason...

**Comment by pwtsai** [comment]
on the current VM?  or your testing host?

**Comment by holishing** [comment]
On my testing host in Virtual-Box <br>(`Linux debian 4.9.0-3-686-pae #1 SMP Debian 4.9.30-1 (2017-06-04) i686 GNU/Linux`) .
I'll post some compiling logs on gist and link here later.

**Comment by holishing** [comment]
temporary fixed in 78b4697
ref: https://www.ptt.cc/bbs/C_and_CPP/M.1465931381.A.BCD.html
