### ISSUE TITLE
site backup

### ISSUE THREAD

**Issue by itscache** [ccns/dreamlandbbs#7]
@holishing : any ideas?

**Comment by holishing** [comment]
1. split to different part + tarball (`*.tar.gz`) to backup to offline storage
2. copy to nfs machine

**Comment by itscache** [comment]
ok, it seems like we need the nfs...

**Comment by itscache** [comment]
Got one old Synology NAS and two new HDDs. Can you setup it in the club room?

**Comment by holishing** [comment]
Ok, I'll try it.

**Comment by itscache** [comment]
Okay, I will prepare it soon. 
By the way, we need an available IP... @HexRabbit where are u~~~

**Comment by itscache** [comment]
@holishing hardware is ready, let me know the available IP configuration first. I will also pre-config an admin account for u.

**Comment by itscache** [comment]
@holishing Bad news, @HexRabbit just told me that the admin would like to give us one private IP and ask us to use a "port forwarding gateway" to make NFS connection. Well, the admin seemed to have some misunderstanding. I do respect to this decision, while it makes things complicated. Please try contacting him and explaining why we need a public IP, thanks.

**Comment by holishing** [comment]
Already test running in `crontab` , please help check again, thanks!
