### ISSUE TITLE
SSL cert

### ISSUE THREAD

**Issue by itscache** [ccns/dreamlandbbs#8]
![webssl](https://user-images.githubusercontent.com/584470/29851835-ea5b28ee-8d68-11e7-9617-589f52cc8965.png)

should we add both ccns.cc bbs.ccns.cc into the SSL cert of BBS host ?

or we can consider apache to redirect the request: 

    RewriteEngine on
    RewriteBase /
    RewriteCond %{HTTPS} !on
    RewriteCond %{SERVER_PORT} !^80$
    RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}

**Comment by holishing** [comment]
I prefer to redirect to `https://bbs.ccns.cc`

**Comment by itscache** [comment]
okay, pleased try it.

**Comment by itscache** [comment]
okay, please try it.

**Comment by holishing** [comment]
http://ccns.cc can be redirected to https://bbs.ccns.cc now.
https://ccns.cc still has cert problem before redirecting.

Still trying "mod_rewrite" ... or waiting for [Wildcard Certificates for Let's Encrypt](https://letsencrypt.org/2017/07/06/wildcard-certificates-coming-jan-2018.html)

**Comment by itscache** [comment]
The explorer should check the input URL and corresponding cert before starting redirection.
Is it possible to apply/re-organize the cert with ccns.cc +  bbs.ccns.cc (alias) ?
(For me, I have a Let's Encrypt cert including abc.im and www.abc.im)

**Comment by holishing** [comment]
ok, done

**Comment by itscache** [comment]
great job!
